FROM node:20-alpine3.16 AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
# sudo apt update
RUN apk update

# pdftk
RUN apk add openjdk8
RUN wget https://gitlab.com/pdftk-java/pdftk/-/jobs/924565145/artifacts/raw/build/libs/pdftk-all.jar
RUN mv pdftk-all.jar /usr/local/bin/pdftk.jar

RUN echo '#!/bin/sh' > /usr/local/bin/pdftk
RUN echo 'java -jar /usr/local/bin/pdftk.jar "$@"' >> /usr/local/bin/pdftk
RUN chmod 775 /usr/local/bin/pdftk*

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json ./
RUN yarn install

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN yarn prisma:generate
RUN yarn build

# If using npm comment out above and use below instead
# RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# write a log to view the current directory
RUN ls -la /app

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/.next/server ./.next/server
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma/schema

# USER nextjs (We need root currently for fs permissions)

EXPOSE 3000

ENV PORT 3000

CMD ["node", "server.js"]

# docker build -t nextjs-docker . && docker run -p 3000:3000 nextjs-docker --name nextjs-docker